//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.mercaderia.bono.Entidades.ModeloEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroIngreso
    {
        public int codRegistro { get; set; }
        public int codUsuario { get; set; }
        public string codInstitucion { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan hora { get; set; }
        public string temperatura { get; set; }
        public string oxigenacion { get; set; }
    
        public virtual Institucion Institucion { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
